version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
  app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis

